### ISSUE TITLE
Recursively find files

### ISSUE THREAD

**Issue by steevanbarboyon** [maglnet/ComposerRequireChecker#279] opened 2021-07-01 07:48 UTC
Hi,

With `scan-files` I can't recursively find files: `foo/*.php` will only search in `foo` directory, not in subdirectories.

Ho can I do it?

Thanks

**Comment by DanielBadura** [comment] 2021-07-01 08:13
`scan-files` follow the glob pattern. So as far as i know it should be possible but never tried it myself or have seen it in the tests here. See here the glob pattern syntax: https://github.com/webmozarts/glob

`/foo/**/*.php` should maybe do the trick.

**Comment by steevanb** [comment] 2022-03-28 15:07
Ok thanks, you can close this issue :)

**Comment by DanielBadura** [comment] 2022-03-28 15:28
Did it worked out?

**Comment by crocodele** [comment] 2022-10-20 11:44
I can confirm that `foo/**/*.php` works for me. I guess this issue can be closed by someone with the power to do so. :slightly_smiling_face:

**Closed as completed** 2022-10-20 12:13 UTC
Labels: question
