### ISSUE TITLE
Useless dependencies option

### ISSUE THREAD

**Issue by soullivaneuh** [maglnet/ComposerRequireChecker#51] opened 2018-01-24 10:05 UTC
It would be a great addition to be able to list useless dependencies. I mean an required dependency with no symbol usage at all.

Of course, it should be optional and the configuration file should accept packages to ignore.

Some packages could just provide configuration file or whatever not related to PHP directly, but used. This case would be a false positive.

**Comment by Ocramius** [comment] 2018-01-24 10:29
This is problematic due to how composer dependencies work, as sometimes you have to require a dependency, and then a third-party package performs a lookup to see if a certain HTTP client or extension is available, then looks for polyfills and so on.

This means that the useless packages would be filled with potentially dangerous false-positives.

**Comment by mindplay-dk** [comment] 2018-02-22 12:44
> This means that the useless packages would be filled with potentially dangerous false-positives.

That fact makes it perhaps not useful for automation, but yhere could still be an option to request this check on demand - usually the maintainer is going to be able to tell false positives from real ones, so this check could definitely be useful in my opinion.

For example, after a large refactoring, such as splitting off certain members to a separate package - it's often hard to keep track of the dependency changes in that situation.

**Comment by Soullivaneuh** [comment] 2018-02-22 18:54
> This means that the useless packages would be filled with potentially dangerous false-positives.

@mindplay-dk Well explained what I think about that.

This is also why I said the configuration file should accept packages to ignore.

**Comment by MidnightDesign** [comment] 2019-03-25 11:28
Duplicate of #14?

**Comment by bobvandevijver** [comment] 2021-03-06 18:32
@soullivaneuh  Would https://github.com/composer-unused/composer-unused help for your case?

**Comment by SvenRtbg** [comment] 2021-05-04 12:34
> Would https://github.com/composer-unused/composer-unused help for your case?

I'd recommend that tool, too, even though it is only just starting and has some issues, errors and unresolved edge cases. 

I have them both running in an automated job, so using one or two tools is no big deal. And I can imagine that these two tools have way different approaches due to their different nature. Keeping them separate will probably reduce overall complexity. ;)

**Comment by mvhirsch** [comment] 2024-11-12 09:13
I'm using both since two years as companion on each project I actively work on: this and `composer-unused` to maintain a clean composer.json. To be honest: I think they make a good team. As in Unix philosophy: 

> make each program do one thing well.

I suggest for closing this issue as out of scope. Use `composer-unused` in such cases instead. WDYT?

**Comment by Ocramius** [comment] 2024-11-12 12:49
Closing indeed :)

**Closed by Ocramius** 2024-11-12 12:49 UTC
Labels: enhancement, question
