### ISSUE TITLE
Segfault When Running Against Repo that includes Faker

### ISSUE THREAD

**Issue by edmondscommerce** [maglnet/ComposerRequireChecker#102] opened 2019-02-05 12:35 UTC
Here is some strace output:

```open("/home/ec/proxies/vendor/fzaninotto/faker/src/Faker/Provider/nl_BE/Text.php", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0644, st_size=1009973, ...}) = 0
lseek(8, 0, SEEK_CUR)                   = 0
fstat(8, {st_mode=S_IFREG|0644, st_size=1009973, ...}) = 0
read(8, "<?php\n\nnamespace Faker\\Provider\\"..., 8192) = 8192
read(8, "    *       *       *       *   "..., 8192) = 8192
read(8, "zijn. Gij weet\nniet wat een uil "..., 8192) = 8192
read(8, "d, ik heb zes duiten verdiend, s"..., 8192) = 8192
read(8, "in de vaart, doch in de beurzen\n"..., 8192) = 8192
read(8, "heelt er toch, man? vroeg zij. G"..., 8192) = 8192
read(8, "ten\nopgebrand waren, toen die va"..., 8192) = 8192
read(8, " ezel weer thuis kwam met een za"..., 8192) = 8192
read(8, "an de markt was een schoone lijn"..., 8192) = 8192
read(8, "en ledigen\nkorf, en gansch ineen"..., 8192) = 8192
read(8, "hing\neen walm van verkoold haar."..., 8192) = 8192
read(8, " haar aan zich zedig te kleeden "..., 8192) = 8192
read(8, "at er, gansch Vlaanderenland\ndoo"..., 8192) = 8192
read(8, "deed het\ndicht. Klaas en Soetkin"..., 8192) = 8192
read(8, "hij ging Uilenspiegel als\nketter"..., 8192) = 8192
read(8, "antwoordde, dat\nde broeders van "..., 8192) = 8192
read(8, "broeder van de Goede Tronie, roe"..., 8192) = 8192
read(8, "an hekserij en verklaarde, dat\nz"..., 8192) = 8192
read(8, "lden uit om die bogen te betalen"..., 8192) = 8192
read(8, "ltering, ziet; dan neemt zij\nijl"..., 8192) = 8192
read(8, " Karel de stede\nzou komen bezoek"..., 8192) = 8192
read(8, " paling en karpers.\n\nUilenspiege"..., 8192) = 8192
read(8, "n. Teederlijk zag de vorstinne h"..., 8192) = 8192
read(8, "wiegelende schuitjes en naar de\n"..., 8192) = 8192
read(8, "soms den verkeerden man. Hebt gi"..., 8192) = 8192
read(8, "n een iegelijk, en inzonderheid "..., 8192) = 8192
read(8, "l vol vet, in denwelken\nmen olie"..., 8192) = 8192
read(8, " halven dag. En 'k heb\ntienduize"..., 8192) = 8192
read(8, " ezel?\n\nUilenspiegel antwoordde:"..., 8192) = 8192
read(8, "ellenden\nblik in zijne sluwe, wr"..., 8192) = 8192
read(8, " altijd op hunne vrijheden, keur"..., 8192) = 8192
read(8, "el, met een paar gulden zou ik\ne"..., 8192) = 8192
read(8, "lakjes\nop den weg lieten vallen,"..., 8192) = 8192
read(8, "d naar den stal.\n\nDaar streek hi"..., 8192) = 8192
read(8, "e gezellen de hand niet geleend."..., 8192) = 8192
read(8, "ang en hoorde Klaas met den\nvree"..., 8192) = 8192
read(8, "roppelen uit te halen en lokte e"..., 8192) = 8192
read(8, "iegel en sprak:\n\n--Mijn zoon, di"..., 8192) = 8192
read(8, ",\nmoet gij het zeggen, opdat wij"..., 8192) = 8192
read(8, "iden zwaar zijn, zult gij, zoo g"..., 8192) = 8192
read(8, "e\nprivileges, aan Zijne Koninkli"..., 8192) = 8192
read(8, "en, alle ellenden geproefd heeft"..., 8192) = 8192
read(8, "Hij schreeuwt als een nachtuil o"..., 8192) = 8192
read(8, "t doet mij meer genoegen\nvoor u "..., 8192) = 8192
read(8, "jne een grijsachtig vocht, dat z"..., 8192) = 8192
read(8, "tonden en eene menigte geesten i"..., 8192) = 8192
read(8, " een stuk\nverkenslever, en hij v"..., 8192) = 8192
read(8, " op een lam een arent,\n    Viel "..., 8192) = 8192
read(8, "t, of ik uw lief gelaat ooit wed"..., 8192) = 8192
read(8, "n \"geuzen\" geheeten en genaamd t"..., 8192) = 8192
read(8, "oesting,\nde oorlog en de val van"..., 8192) = 8192
read(8, "arheid.\n\nJong en poezele kwezelk"..., 8192) = 8192
read(8, "Leve de geus!\" En er blijft\ngeen"..., 8192) = 8192
read(8, "? vroeg een stadsserjant.\n\n--Ik "..., 8192) = 8192
read(8, "t hij het\nvijandelijke leger zal"..., 8192) = 8192
read(8, "andaag kost hij u geen duit, spr"..., 8192) = 8192
read(8, " en vleesch moeten geven. En ald"..., 8192) = 8192
read(8, "emd en\nzijn armen, waren vettig "..., 8192) = 8192
read(8, "e rampspoed is gekomen voor den\n"..., 8192) = 8192
read(8, "e genoemd zijn, tot de straffen "..., 8192) = 8192
read(8, "e wijnkannetjes, tweemaal voor z"..., 8192) = 8192
read(8, "eerdig uitziet,\ndaar hij altijd "..., 8192) = 8192
read(8, " vier zware\nkanonnen, en met vee"..., 8192) = 8192
read(8, "ood Uilenspiegel het graf te ver"..., 8192) = 8192
read(8, " vuurroer en schoot naar de zwar"..., 8192) = 8192
read(8, "onderbussen, de\nsakers, de klein"..., 8192) = 8192
read(8, "degen voerden, gaven fluitend he"..., 8192) = 8192
read(8, "p een van de peerden\nder soldate"..., 8192) = 8192
read(8, "iep:\n\n--Vaarwel, heer, dat de li"..., 8192) = 8192
read(8, "n.\n\n--Zegent mij dan ten minste,"..., 8192) = 8192
read(8, "g, zoo smakelijk en zoo fijn van"..., 8192) = 8192
read(8, " hun\nde minste moeilijkheid aan."..., 8192) = 8192
read(8, "vermogen niets tegen twee mannen"..., 8192) = 8192
read(8, "plimenten van mijnen baas en hij"..., 8192) = 8192
read(8, "vrije mannen, en gij zult ook an"..., 8192) = 8192
read(8, "den zij aan heure rokken gebonde"..., 8192) = 8192
read(8, "et\ndikke, bloedroode lippen, en "..., 8192) = 8192
read(8, "n gezien, die op ezelen reden; s"..., 8192) = 8192
read(8, "mager peerd van de eene naar de "..., 8192) = 8192
read(8, "chept door den hertog\nvan Lothar"..., 8192) = 8192
read(8, "het droog\nwas, beschilderde hij "..., 8192) = 8192
read(8, "r God niet verschijnen,\nbeladen "..., 8192) = 8192
read(8, "wapend\nmet zweerden, met bussen,"..., 8192) = 8192
read(8, "n al te talrijk, sprak de oude m"..., 8192) = 8192
read(8, "\303\263r zij naar\n't galgeveld trekke"..., 8192) = 8192
read(8, "rinken! zeiden de serjanten.\n\n--"..., 8192) = 8192
read(8, "ak:\n\n--Gij zijt hier allen in on"..., 8192) = 8192
read(8, "Damme en in de omstreken,\nafschu"..., 8192) = 8192
read(8, ".\n\n--Maar reeds heeft hij weer m"..., 8192) = 8192
read(8, "enspiegel tot den zwerver:\n\n--Wa"..., 8192) = 8192
read(8, "j het waarschijnlijk is,\ndie het"..., 8192) = 8192
read(8, "s. Zij\nook scheen waanzinnig; zi"..., 8192) = 8192
read(8, "isschers vreezen den\nweerwolf me"..., 8192) = 8192
read(8, "vangene uit de val\nverlost, en t"..., 8192) = 8192
read(8, "wafelijzer met wreede tanden te "..., 8192) = 8192
read(8, " als de\nhond aan zijn been houdt"..., 8192) = 8192
read(8, "onder mijne\noogen? En als zij mi"..., 8192) = 8192
read(8, "t ik uw\nglanzend gelaat zie. Doe"..., 8192) = 8192
read(8, "de wateren vergiftigden, monnike"..., 8192) = 8192
read(8, "zij, zoo heur zwarte bruidegom h"..., 8192) = 8192
read(8, "deken van Heist! Hoeft een oprec"..., 8192) = 8192
read(8, "op dewelke de rechters\nwaren gez"..., 8192) = 8192
read(8, "ppen, belladonna en datura.\n\n..."..., 8192) = 8192
read(8, "hij\nmikt, en, als in boter, een "..., 8192) = 8192
read(8, "e hij overhad voor zich en voor "..., 8192) = 8192
read(8, "d was om de straf te volbrengen."..., 8192) = 8192
read(8, "den armen Lamme, die, getrouwd z"..., 8192) = 8192
read(8, "menschen. Zij leven van de klein"..., 8192) = 8192
read(8, " maanden, wederstaan wij met dui"..., 8192) = 8192
read(8, " Wie heeft de zijden en\nlakensch"..., 8192) = 8192
read(8, "ijn gezwollen voeten en zijn loo"..., 8192) = 8192
read(8, "ls bij hoopen naast de affuiten "..., 8192) = 8192
read(8, ". Wie zal hun den nek omwringen?"..., 8192) = 8192
read(8, "et\nvreemdelingen. Bijt, hertog, "..., 8192) = 8192
read(8, " op uwe wond.\n\nToen Lamme zijne "..., 8192) = 8192
read(8, " krijgen\ngeld om de soldaten te "..., 8192) = 8192
read(8, "ver. Ja, op die goede en brave s"..., 8192) = 8192
read(8, " kunt: hoe meer gij eet,\nhoe lie"..., 8192) = 8192
read(8, "l weegt hij? Driehonderd veertie"..., 8192) = 8192
read(8, "ulden per maand: Broer Cornelis "..., 8192) = 8192
read(8, "e sprong op van geluk en riep bl"..., 8192) = 8192
read(8, "den moordenaar\nmet drie kogels i"..., 8192) = 8192
read(8, " Lelie, vloo, de geheimenis,\n   "..., 8192) = 8192
read(8, " tranen en snikken.\n\nDe burgemee"..., 8192) = 2357
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
close(8)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7fff1d5c9f70} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

**Comment by Ocramius** [comment] 2019-02-05 12:37
Possibly more interesting as php-src bug, not a bug in here.

**Comment by edmondscommerce** [comment] 2019-02-05 12:37
removing faker from composer.json resolves it

**Comment by Ocramius** [comment] 2019-02-05 12:49
Yes, but that's not the root cause: it's possibly the parser getting stuck
on utf8 data.

**Comment by edmondscommerce** [comment] 2019-02-05 17:23
Fair enough

Any chance we could have some config to skip certain files to be able to work around this kind of issue?

**Comment by Ocramius** [comment] 2019-02-05 17:31
I'd rather fix the bug. Working around it just dumps the issue onto the
next faker user.

**Comment by edmondscommerce** [comment] 2019-02-06 17:57
makes sense

Would you like me to raise a PHP bug? to be honest I'm not totally sure how to present it

**Comment by Ocramius** [comment] 2019-02-09 15:47
Yes, raising a PHP bug with a reproducible example would be best.

**Comment by Ocramius** [comment] 2019-02-09 15:47
Meanwhile, closing as `invalid` here, since the source of the bug is in php-src

**Closed by Ocramius** 2019-02-09 15:47 UTC
Labels: bug, invalid
