### ISSUE TITLE
Hard error don't show which file was tried to be analyzed

### ISSUE THREAD

**Issue by mfn** [maglnet/ComposerRequireChecker#112] opened 2019-07-12 09:33 UTC
Tried it the first time today, was greeted with this (already added `-vvv` to get a stacktrace):
```
$ vendor/bin/composer-require-checker -vvv
ComposerRequireChecker 0c658da3e-dev
Collecting defined vendor symbols...
In ParserAbstract.php line 315:

  [PhpParser\Error]
  Syntax error, unexpected ';', expecting T_VARIABLE or '{' or '$' on line 4


Exception trace:
 () at /vagrant/project/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:315
 PhpParser\ParserAbstract->doParse() at /vagrant/project/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:158
 PhpParser\ParserAbstract->parse() at /vagrant/project/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php:51
 PhpParser\Parser\Multiple->tryParse() at /vagrant/project/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php:32
 PhpParser\Parser\Multiple->parse() at /vagrant/project/vendor/maglnet/composer-require-checker/src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php:35
 ComposerRequireChecker\ASTLocator\LocateASTFromFiles->__invoke() at /vagrant/project/vendor/maglnet/composer-require-checker/src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRoots.php:27
 ComposerRequireChecker\DefinedSymbolsLocator\LocateDefinedSymbolsFromASTRoots->__invoke() at /vagrant/project/vendor/maglnet/composer-require-checker/src/ComposerRequireChecker/Cli/CheckCommand.php:79
 ComposerRequireChecker\Cli\CheckCommand->execute() at /vagrant/project/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /vagrant/project/vendor/symfony/console/Application.php:921
 Symfony\Component\Console\Application->doRunCommand() at /vagrant/project/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /vagrant/project/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /vagrant/project/vendor/maglnet/composer-require-checker/bin/composer-require-checker.php:32
 include() at /vagrant/project/vendor/maglnet/composer-require-checker/bin/composer-require-checker:3

check [--config-file CONFIG-FILE] [--ignore-parse-errors] [--] [<composer-json>]
```
After I changed `\ComposerRequireChecker\ASTLocator\LocateASTFromFiles::__invoke` to this:
```php
    public function __invoke(Traversable $files): Traversable
    {
        foreach ($files as $file) {
            echo "$file\n";
            yield $this->parser->parse(file_get_contents($file), $this->errorHandler);
        }
    }
```
I was able to locate the file in question => it's another vendor file:
```
…
/vagrant/project/vendor/guzzlehttp/guzzle/src/Client.php
/vagrant/project/vendor/jakub-onderka/php-parallel-lint/./bin/skip-linting.php
/vagrant/project/vendor/jakub-onderka/php-parallel-lint/./tests/examples/example-03/example.php

In ParserAbstract.php line 315:

  [PhpParser\Error]
  Syntax error, unexpected ';', expecting T_VARIABLE or '{' or '$' on line 4
```
That's a linter project whose tests contain invalid code.

Nevertheless, two suggestions:
- don't make me have to use `-vvv` to get a stacktrace
- report the file which has an error

**Comment by mfn** [comment] 2019-07-12 09:39
The problem of the other project is also that it does not differentiate src from test files because it contains only a single `autoload` for everything => reported as https://github.com/JakubOnderka/PHP-Parallel-Lint/issues/140

**Comment by Ocramius** [comment] 2019-07-12 11:23
Duplicate of https://github.com/maglnet/ComposerRequireChecker/issues/92

**Closed by Ocramius** 2019-07-12 11:23 UTC
